version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telly
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - telly-db:/var/lib/mysql
  telly_web:
    build:
      dockerfile: docker/Dockerfile
      context: ./
    environment:
      SHELL: /bin/bash
    volumes:
      - ./app:/work/app
      - ./html:/work/html
      - ./public:/work/public
      - ./themes:/work/themes
    depends_on:
      - db
    ports:
      - "8100:80"
    links:
      - db
volumes:
  telly-db:
